### PR TITLE
Added draw_sprite_h_flip and draw_sprite_v_flip

### PR DESCRIPTION
**Pull request by danwardvs**
A couple drawing functions from Allegro 4

### CODE REVIEW

**Comment by TheSos** [comment]
Hmm... I think it should be a paramemter in draw_sprite, the old allegro separate functions were like this for performance reasons and there's no reason to keep it this way, IMO. 
Or perhhaps make a scaled_sprite_xy where you can specify x and y scale separately and that lets you flip by putting in a negative scale value?
What do you think?

**Comment by danwardvs** [comment]
I guess it depends on where you're going with this project. I've used it a lot and I think that keeping this in for porting from Allegro 4 would be nice. Another thing is when you draw a flipped image it doesn't draw from the top left anymore, so I had to add the width or the height when it flips.

**Comment by TheSos** [comment]
I didn't really wanted to aim for it to be aimed at porting, I kind of wanted it to be more of an entry point for gamedev newcomers as well! There are many diferences between this and original already
draw_sprite in itself is different, since it draws the sprite centered, not from the corner!
I think I really want to go with scaled_sprite_xy() and rotate_scaled_sprite_xy() instead of this, or maybe have scaled_sprite accept both one and two scaling attributes! I hope you don't hate me for that. :(

**Comment by danwardvs** [comment]
Alright. I totally understand, thanks anyway. I promise I won't hate you. You did make McPixel after all.

**Pull request closed without merging**
