### PR TITLE
Documentation fixes

### PR DESCRIPTION
**Pull request by ratkingsminion**
Mostly minor fixes in the documentation comments (missing @returns, and so on)
A few changes in parameter naming for consistency
Also removed a "return" in install_int(), as it only calls install_int_ex(), which returns nothing

### CODE REVIEW

**Comment by TheSos** [comment]
You fixed the *_sprites the wrong way! All were supposed to be centred! :P I fixed them back and added negatyive scaling ability too! Part of this pull I can't merge now, thus!

**Comment by ratkingsminion** [comment]
I better stop trying to "fix" things until I know what's supposed to happen. :-P

**Comment by TheSos** [comment]
Anyways, if you can merge that edit with centered sprites, I can pull that! :) Sorry for the confusion!

**Comment by ratkingsminion** [comment]
I'll make a new one

**Pull request closed without merging**
